### ISSUE TITLE
how to compile the model

### ISSUE THREAD

**Issue by heyuanqing007** [pnnl/hexwatershed#1]
1. How should I adjust my Cmakelists.txt configurationdoes?
2. The model's operating system needs Linux and install GDAL before running?
3. Is the hexagon grid file in ShapeFile format and how should I set the property field?

**Comment by changliao1025** [comment]
The HexWatershed model uses an out-of-source approach to compile and build the model, which means you are supposed to build outside the root directory of the git repository. As an example, all the following command can be executed on either a Linux or Mac terminal:

    cd ..
    mkdir CMake

Then you can place the CMakeLists.txt within the CMake folder. You can copy the example CMakeLists.txt within the repository to the CMake folder as a start.

Make sure the cmake version is above or equal 3.10. 
You need to install gdal 2.3 in the system. (That answers your second question.)
You also need GCC 5.2 or higher.

You need to adjust the source code directory and gdal/gcc path within CMakeLists.txt, basically if you received no warning or error after running:

     cmake CMakeLists.txt
     make

You should see a compiled binary within both CMake folder and the bin within repo directory.

The shapefile should be generated using the MMQGIS plugin (http://michaelminn.com/linux/mmqgis/). It can be run within QGIS.

No field requires edit as long as it has the same spatial reference with the DEM raster data. (That answers your third question.)

**Comment by heyuanqing007** [comment]
Thank you very much for your reply, which is very helpful to me
